# Use root/example as user/password credentials

services:

 db:   # db est le nom du service Docker qui exécute MariaDB
    image: mariadb:11.8.2-noble
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      -  8081:8080
