CREATE DATABASE SA;

CREATE TABLE CLIENT
(
    ID    integer primary KEY NOT NULL AUTO_INCREMENT,
    EMAIL varchar(50)
);
CREATE TABLE SENTIMENT (
    ID integer primary key not null AUTO_INCREMENT,
    TEXTE VARCHAR(50),
    TYPE VARCHAR(10),
    CLIENT_ID INTEGER,
    CONSTRAINT client_fk FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);
